### ISSUE TITLE
Null pointer exception from Enhanced GoControl Thermostat Driver

### ISSUE THREAD

**Issue by ryancasler** [Botched1/Hubitat#5]
Got the following error from my hub today.

![image](https://user-images.githubusercontent.com/30270489/69287519-89b41f00-0bc4-11ea-9a44-1773ff6602be.png)

I wasn't doing anything with the system at that time but I do find it interesting that it happened during the hub's maintenance window.  Just wanted to make sure you were aware in case other folks report seeing the same thing.  I am running on the latest 1.3.1 from July.

**Comment by Botched1** [comment]
Thanks for letting me know, I will take a look. That's a weird place to get a null, I'll have to think on it a little bit.
