### ISSUE TITLE
GE switch driver double tap not functioning correctly 

### ISSUE THREAD

**Issue by kc2h** [Botched1/Hubitat#7]
I am trying to get 2 lights in the same room to come on when either of their switches are double tapped.  I can get the OTHER light to turn on, but not both.

So I have to single tap  to turn the 1st light on then a double tap to turn the 2nd one on.

**Comment by dkattan** [comment]
I believe this is because the logs indicate button 3 is being double tapped but really it’s sending a pushed button 3 and doubleTapped button 1

```groovy

   // Double Tap Up
    if ((cmd.keyAttributes == 3) && (cmd.sceneNumber == 1)) {
		if (logEnable) log.debug "Double Tap Up Triggered"
		if (logDesc) log.info "$device.displayName had Doubletap up (button 3) [physical]"
		result << sendEvent([name: "pushed", value: 3, descriptionText: "$device.displayName had Doubletap up (button 3) [physical]", type: "physical", isStateChange: true])
        result << sendEvent([name: "doubleTapped", value: 1, descriptionText: "$device.displayName had Doubletap up (doubleTapped 1) [physical]", type: "physical", isStateChange: true])
    }
```
The trigger worked when I set it to button 1 doubleTapped
